/-
Copyright (c) 2023 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author : Kevin Buzzard
-/
import Mathlib.Tactic
-- imports all the Lean tactics
import Mathlib.MeasureTheory.MeasurableSpace.Defs

/-

# Measure theory

## Sigma algebras.

A σ-algebra on a type `X` is a collection of subsets of `X` satisfying some
axioms, and in Lean you write it like this:

-/

namespace Section13Sheet1

-- let X be a set
variable (X : Type)

-- ...and let 𝓐 be a sigma-algebra on X
variable (𝓐 : MeasurableSpace X)

/-

Note that `MeasurableSpace` is a *class*, so really we should be writing `[MeasurableSpace X]`,
meaning "let `X` be equipped once and for all with a sigma algebra which we won't give a name to".
But in this sheet we'll consider making them explicitly.

Let's do the following exercise. Show that if `A` is a subset of `X` then `{0,A,Aᶜ,X}`
is a sigma algebra on `X`.

-/
def genBy (A : Set X) : MeasurableSpace X where
  MeasurableSet' S := S = ∅ ∨ S = A ∨ S = Aᶜ ∨ S = ⊤
  measurableSet_empty := by
    simp only [true_or]
  measurableSet_compl := by
    intro s a
    simp only [compl_eq_comm]
    simp only [Set.compl_empty_iff, compl_inj_iff, Set.top_eq_univ, Set.compl_univ_iff]
    simp at a
    tauto

  measurableSet_iUnion := by

    intro f w
    simp only [Set.top_eq_univ] at w ⊢
    set u := ⋃ i, f i with u_def

    have key {q} (hq : ∃i, f i = q ) : q ⊆ u := by
      obtain ⟨j,j_spec⟩ := hq
      rw [←j_spec]
      exact Set.subset_iUnion f j






    by_cases ht : ∃i, f i = Set.univ
    {
      simp [top_unique (key ht)]
    }
    simp only [not_exists] at ht
    simp only [ht, or_false] at w
    by_cases hA : ∃i, f i = A
    {
      have tA : A ⊆ u := key hA
      by_cases hC : ∃i, f i = Aᶜ
      {
        suffices u = Set.univ by tauto
        have tC : Aᶜ ⊆ u := key hC
        have u1: A ∪ Aᶜ = Set.univ := Set.union_compl_self A
        have u2: A ∪ Aᶜ ⊆ u := by exact Set.union_subset tA tC
        have u3: Set.univ ⊆ u := by simpa only [u1] using u2
        exact Set.univ_subset_iff.mp u3
      }
      simp only [not_exists] at hC
      simp only [hC, or_false] at w

      suffices u = A by tauto
      refine (Set.Subset.antisymm tA ?_).symm
      simp only [Set.iUnion_subset_iff]
      intro i
      specialize w i
      cases w
      {
        rename_i h
        rw [h]
        exact Set.empty_subset A
      }
      rename_i h
      rw [h]

    }
    simp only [not_exists] at hA
    simp only [hA, false_or] at w

    by_cases hC : ∃i, f i = Aᶜ
    {

      suffices u = Aᶜ by tauto
      have tC : Aᶜ ⊆ u := key hC
      refine (Set.Subset.antisymm tC ?_).symm
      simp only [Set.iUnion_subset_iff]
      intro i
      specialize w i
      cases w
      {
        rename_i h
        rw [h]
        exact Set.empty_subset _
      }
      rename_i h
      rw [h]
    }
    simp only [not_exists] at hC
    simp only [hC, or_false] at w

    suffices u = ∅ by tauto
    simp only [Set.iUnion_eq_empty]
    exact w

-- An alternative approach to defining the sigma algebra generated by `{A}` is just
-- to use `MeasurableSpace.generateFrom`:
example (A : Set X) : MeasurableSpace X :=
  MeasurableSpace.generateFrom {A}

-- But the problem with that approach is that you don't get the actual sets
-- in the sigma algebra for free. Try this, to see what I mean!
example (A : Set X) :
    (MeasurableSpace.generateFrom {A}).MeasurableSet' =
    ({∅, A, Aᶜ, ⊤} : Set (Set X)) := by
  ext x

  rw [Set.insert_def]
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
  rw [setOf]

  sorry

end Section13Sheet1
